# Generated by Django 2.1.2 on 2018-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181102_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expiration',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '아주 중요'), (2, '중요'), (3, '보통'), (4, '별로 안 중요')], db_index=True, default=3),
        ),
    ]
